### ISSUE TITLE
Change polling frequency?

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdevbot#34]
It seems that this new bot does not (and will not?) create a lot of traffic.  Perhaps we can risk increasing the polling frequency?  I noticed that maybe 150 requests were made in an hour with the current 90 second polling frequency.  Perhaps we can change it to a 30 second polling frequency.

**Comment by kmpaul** [comment]
@andersy005:  We should watch the Heroku logs now that the bot is live and not idling.  If the logs show that the rate limits are not being reached by a *lot*, then we can increase the polling frequency.  If the logs show the rate limits are being reached, then we need to decrease the polling freqency.

**Comment by kmpaul** [comment]
Ok.  I've been watching the logs since enabling PaperTrail on the Heroku app on September 8, 2020.  Through to today, the highest REST API request rate was 714 requests/hour and the highest GraphQL request rate was 119 requests/hour.  We currently are at a polling period of 60 seconds...  Should we try decreasing the polling period to 30 seconds?  (CC @andersy005)

**Comment by kmpaul** [comment]
@andersy005: I've looked at the logs more and the lowest the rate limits every get is 4286 (of 5000) for the core (REST API) rate limits.  I've changed the polling to 15 seconds, now, and I will continue to watch it.  I'm a little worried that the bot is only ever sending 714 requests/hour *max*, even after increasing the polling frequency.  There are no errors reported in the logs.  So, let's watch it and make sure it is working correctly.

**Comment by andersy005** [comment]
> There are no errors reported in the logs. So, let's watch it and make sure it is working correctly.

I will be monitoring it for the next few days

**Comment by kmpaul** [comment]
I noted that the debug-level output is filling out 10MB/day limit of free PaperTrail log storage. So, we may have to limit the output.

**Comment by kmpaul** [comment]
Lots more output with a 10 second polling period.

**Comment by kmpaul** [comment]
Ok.  With a 10 second polling period for the last week or more, the CORE (REST API) polling rate is roughly 2000 requests per hour (of 5000 allowed).  This seems like a good place to stop.  Closing the issue.
