### ISSUE TITLE
Create an aggregate board

### ISSUE THREAD

**Issue by kmpaul** [NCAR/xdevbot#36]
I think we should have an "aggregate" board, in addition to the campaign-specific boards we currently have.  I don't think this board should be something that the GitHub actions actually knows about.  Instead, I think that anything that happens on another board should also happen on the aggregate board.

I'm not sure how much we want to make this functional, because completely mirroring a card on the aggregate board with one on another board would require that the xdev repo have a webhook installed for all "project card" events.  And we might need the bot to respond to "project_card" event actions like "created", "edited" (?), "moved".

**Comment by kmpaul** [comment]
It seems that #40 might be working.  So, creation of the aggregate board might be a possibility.

What should we call the aggregate board?

@andersy005

**Comment by andersy005** [comment]
> What should we call the aggregate board?

Is this https://github.com/NCAR/xdev/projects/10 what you ended up choosing? If so, 👍 from me

**Comment by kmpaul** [comment]
Yes.  And now that the multiple project boards appear to be staying in sync with each other, I just modified the add/remove repository GitHub action to automatically add/remove repos to the "main" board whenever a repo is added/removed to/from a campaign project board.  Do you think that makes sense?

**Comment by kmpaul** [comment]
...Obviously, with this approach, it will take some time to populate the Main Board.  Maybe we can create a quick script to "initialize" the board with the content from the other boards?  Or we can just wait.

**Comment by andersy005** [comment]
> ...Obviously, with this approach, it will take some time to populate the Main Board. Maybe we can create a quick script to "initialize" the board with the content from the other boards? Or we can just wait.

I'm happy to put this script together

**Comment by kmpaul** [comment]
@andersy005: If you do, make sure that the "user" that adds the cards is the `xdev-bot` user.  Otherwise the cards will be treated as "non-bot" cards and handled by polling only.  Since polling seems flaky at the moment, it would be best to make sure that polling is used to a limited extent.

**Comment by kmpaul** [comment]
I think this is now complete with the latest commits to `master`.
